[build]
builder = "RAILPACK"
buildEnvironment = "V3"
buildCommand = "cd ui && bun install && bun run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn -w 4 -b 0.0.0.0 'api_server:create_app()'"
sleepApplication = false
useLegacyStacker = false
multiRegionConfig = {"us-east4-eqdc4a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
